version: '3.3'

services:
  airflow:
    build: ./resources/docker_setup/airflow
    image: my_airflow_image
    ports: 
      - target: 8080
        published: 8080
    container_name: my_airflow_container
    volumes: 
      - ./dags:/usr/local/airflow/dags/
      - ./resources:/usr/local/airflow/resources/
  
  mysql:
    image: mysql:5.7
    container_name: mysql_container
    ports: 
      - 3307:3306
    environment: 
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    volumes: 
      - ./resources/docker_setup/mysql:/docker-entrypoint-initdb.d
      - mysql-data:/var/lib/mysql

volumes: 
  mysql-data:
